### ISSUE TITLE
Documentation de l'intégration de la marque blanche en Iframe

### ISSUE THREAD

**Issue by spelhate** [megalis-bretagne/opendata-documentation#2]
La documentation est manquante sur ce point : https://opendata-megalis.readthedocs.io/fr/latest/utilisateur/publication.html#visualiser-et-recuperer-le-code-de-la-marque-blanche
Je propose de documenter cette partie via une PR

**Comment by lvinsonneau** [comment]
En fait, j'avais arrêté de renseigné le readthedoc côté utilisateur, car pour nous c'est un doublon de nos tutoriels présents ici :  
https://services.megalis.bretagne.bzh/?cat=4469&s=&post_type=search_tutos

Mais sinon, le tutoriel sur la marque-blanche opendata est là :  https://services.megalis.bretagne.bzh/tutoriel/utiliser-la-marque-blanche-opendata/

**Comment by spelhate** [comment]
PR proposée : https://github.com/megalis-bretagne/opendata-documentation/pull/4
Démo : https://delib.csm.ovh/documentation_opendata/utilisateur/publication.html#visualiser-et-recuperer-le-code-de-la-marque-blanche
